### ISSUE TITLE
Dev/Stage environment for ODH Jupyterhub

### ISSUE THREAD

**Issue by tumido** [open-services-group/byon#20]
**Is your feature request related to a problem? Please describe.**
I want:
- A stage environment deploying BYON on top of ODH with JupyterHub deployment
- A clean, easy and reproducible procedure how to stand up a dev environment that deploys ODH operator + JupyterHub + BYON for dev purposes 

**Describe the solution you'd like**
For stage environment provide a namespace or cluster in Operate First with a BYON deployment from thoth-station/helm-charts master
For dev environment provide a guide/steps and a kustomize to apply to get a dev environment up and running in no time. A dev file for code ready containers maybe? 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tumido** [comment]
My current dev environment configuration uses:

```yaml
# kfdef.yaml
---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: "https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.1"
```

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/operate-first/apps/master/cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/subscription.yaml
  - kfdef.yaml
  - https://raw.githubusercontent.com/thoth-station/helm-charts/main/charts/meteor-pipelines/templates/byon-validate-jupyterhub-image.yaml
  - https://raw.githubusercontent.com/tumido/helm-charts/byon-import-image/charts/meteor-pipelines/templates/byon-import-jupyterhub-image.yaml
  - https://raw.githubusercontent.com/tumido/helm-charts/byon-import-image/charts/meteor-pipelines/templates/byon-noop.yaml
```
